"""
One-shot backfill: copy embedding vectors from S3 JSON files into the
new embedding_cache.embedding_vector (pgvector) column.

Why: the original cache stored each vector as an individual S3 JSON
object (~30 KB) with embedding_cache mapping hash → s3_path. The
worker now reads/writes the vector inline via pgvector, so existing
rows need their vector copied into the new column before we drop
s3_path and delete the S3 prefix.

Idempotent: only processes rows where embedding_vector IS NULL. Safe
to re-run after partial failures or when new legacy entries are added.

Usage (inside the worker container):
    python -m src.backfill_embedding_cache

Optional flags:
    --batch-size N   rows fetched per DB round-trip (default 500)
    --workers N      parallel S3 GETs per batch (default 16)
    --limit N        stop after N rows have been backfilled
    --dry-run        log what would happen without writing
"""

import argparse
import json
import logging
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone

import boto3

from src.config import S3_BUCKET, S3_REGION
from src.db import get_connection

logger = logging.getLogger(__name__)


def _fetch_pending_batch(cur, batch_size: int) -> list[tuple[int, str, str]]:
    """
    Pull up to batch_size rows that still need their vector backfilled.
    Locks them for the duration of this batch via FOR UPDATE SKIP LOCKED
    so multiple backfill workers can run safely in parallel if needed.
    """
    cur.execute(
        """SELECT id, embedding_hash, s3_path
           FROM embedding_cache
           WHERE embedding_vector IS NULL AND s3_path <> ''
           ORDER BY id
           LIMIT %s
           FOR UPDATE SKIP LOCKED""",
        (batch_size,),
    )
    return cur.fetchall()


def _load_vector_from_s3(s3_client, s3_path: str) -> list[float] | None:
    """
    Download the cached JSON vector from S3. Returns None on missing
    object or malformed payload — caller decides how to handle (we skip
    the row and log; a missing S3 file means the row is unrecoverable
    and will need to be re-generated by Bedrock on its next cache lookup).
    """
    try:
        key = s3_path.replace(f"s3://{S3_BUCKET}/", "")
        response = s3_client.get_object(Bucket=S3_BUCKET, Key=key)
        vector = json.loads(response["Body"].read())
        if not isinstance(vector, list) or not vector:
            logger.warning("Malformed vector at %s (not a non-empty list)", s3_path)
            return None
        return vector
    except Exception as e:
        logger.warning("Failed to load %s: %s", s3_path, e)
        return None


def _vector_to_pg_literal(vector) -> str:
    """Same format used by steps/clustering.py and the embedding step."""
    return "[" + ",".join(str(float(v)) for v in vector) + "]"


def backfill(batch_size: int, workers: int, limit: int | None, dry_run: bool) -> dict:
    """
    Drive the backfill loop. Returns counters for the caller to log.

    Each iteration:
      1. SELECT a batch of NULL-vector rows
      2. Fetch their JSON from S3 in parallel
      3. UPDATE each row with the recovered vector (single transaction)
      4. Commit and continue until no rows remain or --limit hits
    """
    s3 = boto3.client("s3", region_name=S3_REGION)
    counts = {"processed": 0, "updated": 0, "missing_s3": 0, "batches": 0}
    start = time.time()

    while True:
        if limit is not None and counts["updated"] >= limit:
            logger.info("Reached --limit %d, stopping.", limit)
            break

        conn = get_connection()
        try:
            with conn.cursor() as cur:
                rows = _fetch_pending_batch(cur, batch_size)
                if not rows:
                    logger.info("No more rows pending. Done.")
                    break

                counts["batches"] += 1
                logger.info("Batch %d: fetched %d rows", counts["batches"], len(rows))

                # Parallel S3 fetches — strictly read-only on the cache
                # object store, so safe to crank workers up.
                results: dict[int, list[float] | None] = {}
                with ThreadPoolExecutor(max_workers=workers) as executor:
                    futures = {
                        executor.submit(_load_vector_from_s3, s3, s3_path): row_id
                        for row_id, _emb_hash, s3_path in rows
                    }
                    for future in as_completed(futures):
                        row_id = futures[future]
                        results[row_id] = future.result()

                # Apply updates in a single transaction so the batch is
                # atomic — partial failures roll back together and the
                # row stays in NULL state for the next attempt.
                now = datetime.now(timezone.utc)
                batch_updated = 0
                batch_missing = 0
                for row_id, _emb_hash, _s3_path in rows:
                    vector = results.get(row_id)
                    counts["processed"] += 1
                    if vector is None:
                        batch_missing += 1
                        continue
                    if dry_run:
                        batch_updated += 1
                        continue
                    cur.execute(
                        """UPDATE embedding_cache
                           SET embedding_vector = %s::vector, updated_at = %s
                           WHERE id = %s AND embedding_vector IS NULL""",
                        (_vector_to_pg_literal(vector), now, row_id),
                    )
                    batch_updated += 1

                if dry_run:
                    conn.rollback()
                else:
                    conn.commit()

                counts["updated"] += batch_updated
                counts["missing_s3"] += batch_missing
                elapsed = time.time() - start
                rate = counts["processed"] / elapsed if elapsed > 0 else 0
                logger.info(
                    "Batch %d done: updated=%d, missing_s3=%d. "
                    "Total processed=%d, updated=%d, missing=%d. Rate=%.0f rows/s",
                    counts["batches"], batch_updated, batch_missing,
                    counts["processed"], counts["updated"], counts["missing_s3"], rate,
                )
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    return counts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument("--workers", type=int, default=16)
    parser.add_argument("--limit", type=int, default=None,
                        help="Stop after this many rows have been updated")
    parser.add_argument("--dry-run", action="store_true",
                        help="Read S3 + log, but do not commit DB updates")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    logger.info(
        "Starting backfill. batch_size=%d workers=%d limit=%s dry_run=%s",
        args.batch_size, args.workers, args.limit, args.dry_run,
    )

    counts = backfill(args.batch_size, args.workers, args.limit, args.dry_run)
    logger.info("Backfill finished: %s", counts)
    # Non-zero exit if any rows could not be recovered — operator should
    # decide whether the count is acceptable (likely yes — those entries
    # will simply re-generate via Bedrock on next cache miss).
    sys.exit(1 if counts["missing_s3"] > 0 else 0)


if __name__ == "__main__":
    main()
