<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Create the exports table.
 *
 * Records each export file generated by the ExportAndFinalize step.
 * Files are stored in S3; this table holds metadata and pre-signed URL generation info.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('exports', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tenant_id')->constrained('tenants');
            $table->foreignId('pipeline_job_id')->constrained('pipeline_jobs')->cascadeOnDelete();
            $table->string('export_type'); // knowledge_units, enriched_rows, cluster_summary, representative_examples, pipeline_report
            $table->string('format'); // csv, json, html
            $table->string('s3_path');
            $table->string('schema_version')->nullable();
            $table->timestamp('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('exports');
    }
};
