<?php

namespace App\Models;

use App\Models\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Metadata for an exported file generated by the ExportAndFinalize step.
 * The actual file is stored in S3; this record enables pre-signed URL generation.
 */
class Export extends Model
{
    use BelongsToTenant;

    public $timestamps = false;

    protected $fillable = [
        'tenant_id', 'pipeline_job_id', 'export_type',
        'format', 's3_path', 'schema_version', 'created_at',
    ];

    protected $casts = [
        'created_at' => 'datetime',
    ];

    /** The pipeline job that produced this export artifact. */
    public function pipelineJob(): BelongsTo
    {
        return $this->belongsTo(PipelineJob::class);
    }
}
