<?php

namespace App\Models;

use App\Models\Concerns\BelongsToWorkspace;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Tracks the lifecycle of a pipeline execution.
 *
 * Status transitions follow the Job State Machine:
 * submitted -> validating -> preprocessing -> embedding -> clustering
 * -> cluster_analysis -> knowledge_unit_generation -> exporting -> completed
 *
 * pipeline_config_snapshot_json stores an immutable copy of the config
 * used for this run, ensuring reproducibility (Design Principle 1).
 */
class PipelineJob extends Model
{
    use BelongsToWorkspace;

    protected $fillable = [
        'workspace_id', 'dataset_id', 'embedding_id', 'pipeline_config_id',
        'status', 'start_step', 'source_job_id',
        'progress', 'current_action', 'pipeline_config_snapshot_json', 'step_outputs_json',
        'error_detail', 'started_at', 'completed_at',
    ];

    protected $casts = [
        'pipeline_config_snapshot_json' => 'array',
        'step_outputs_json' => 'array',
        'started_at' => 'datetime',
        'completed_at' => 'datetime',
    ];

    /**
     * Valid status transitions as defined in the Job State Machine.
     */
    public const STATUSES = [
        'submitted', 'validating', 'preprocessing', 'embedding',
        'clustering', 'cluster_analysis', 'knowledge_unit_generation',
        'exporting', 'completed', 'failed', 'cancelled',
    ];

    /** The input dataset this job processes. */
    public function dataset(): BelongsTo
    {
        return $this->belongsTo(Dataset::class);
    }

    /**
     * The source job whose embedding output this clustering-only job reuses.
     * Only set when start_step != 'preprocess'.
     */
    public function sourceJob(): BelongsTo
    {
        return $this->belongsTo(PipelineJob::class, 'source_job_id');
    }

    /**
     * Resolve the S3 path to the embedding output for clustering-only dispatch.
     *
     * For a full pipeline job, the path comes from this job's own step_outputs.
     * For a clustering-only job, the path comes from the source job.
     */
    public function resolveEmbeddingS3Path(): ?string
    {
        $source = $this->source_job_id ? $this->sourceJob : $this;
        return $source?->step_outputs_json['embedding']['output_s3_path'] ?? null;
    }

    /**
     * Resolve the embedding_id for clustering-only dispatch.
     * Reads from the source job's pipeline config or step outputs.
     */
    public function resolveEmbeddingId(): ?int
    {
        $source = $this->source_job_id ? $this->sourceJob : $this;
        return $source?->pipeline_config_snapshot_json['embedding_id']
            ?? $source?->step_outputs_json['embedding']['embedding_id']
            ?? null;
    }

    /** The reusable config template this job was created from (if any). */
    public function pipelineConfig(): BelongsTo
    {
        return $this->belongsTo(PipelineConfig::class);
    }

    /** Clusters produced during the clustering step. */
    public function clusters(): HasMany
    {
        return $this->hasMany(Cluster::class);
    }

    /** Knowledge units generated by the LLM analysis step. */
    public function knowledgeUnits(): HasMany
    {
        return $this->hasMany(KnowledgeUnit::class);
    }

    /** Export artifacts (JSON, CSV) created during the export step. */
    public function exports(): HasMany
    {
        return $this->hasMany(Export::class);
    }
}
